	<h3>Tamra</h3> 
	<img src="images/tamra.jpg" alt="" class="thumbnail"/>
	<img src="images/closeup3.jpg" alt="" class="thumbnail"/>
	<img src="images/guate2.jpg" alt="" class="thumbnail"/>
	<img src="images/fam6.jpg" alt="" class="thumbnail"/>
        <div class="expander">
		<p>Tamra Fakhoorian of Graves County is no stranger to traveling to foreign lands, having visited over fifteen countries in addition to a “youthful” journey spent back-packing across South America. She says she never expected a search online to evolve into her most recent expedition with a mission group to highland villages near San Marcos la Laguna, three hours northwest of Antigua in Guatemala. She was searching for information on how to construct a wood fired pizza oven on the internet, when she came across a link that she says opened her eyes and her heart to a group of volunteer, “Masons on a Mission (MOM).”</p>
		<p>Fakhoorian contacted Patrick Manley, the founder/organizer of M.O.M., and learned how his mission group, comprised of professionals from all walks of life (masons, retired teachers, engineers, and even a public relations director), travel to Guatemala to construct wood fired brick stoves. Manley explained that the stoves dramatically improve the health, life expectancy and overall wellbeing of Guatemalan families, particularly those of the women and children. He further explained how he and the volunteers have made an annual trek for the past thirteen years at their own expense and with  no monetary compensation, to build efficient wood burning brick cook stoves for the poverty stricken villagers of Guatemala.</p>
		<p>Fakhoorian told how she joined he mission on their most recent trip on Jan. 12 and returned on Jan. 29, 2012. She says she learned first-hand how to construct several concrete and brick stoves and told how the construction of a single stove costs only $150 each: a small investment that will bring a lifetime of dividends in terms of better health to 34 families in two small villages.</p>
		<p>The families served by the mission are part of Guatemala’s poverty stricken Mayan majority. Sixty percent of Guatemalans own only six percent of the land and survive on less than two dollars a day. Basic resources such as health care, electricity and potable water are extremely scarce. Yet, these people endure, maintaining pride in their ancient languages and rich cultural traditions, while seeking ways to overcome the obstacles of poverty and discrimination by the larger society.</p>
		<p>Manley has organized and led the expeditions to Guatemala to help more than 1,500 families that now have their own hand-built masonry cook stoves. The stoves are more than just a charitable donation for the women, who spend their days bent over open fires in poorly ventilated homes. The cook stoves, call “estufas”, feed their families, but they also save eyes and lungs. Female villagers often appear to be crying because of the long hours spent around open fire pits. Those tears are actually droplets of hot tar which literally burn the surfaces of their eyes. After thirty or forty years of cooking over the open fire pits, many women in the villages go blind, and the children who lend a hand in cooking will lose lung function, from which they will never recover.</p>
		<p>For centuries, the Maya have cooked over three-stone fires built on the dirt floors of household kitchens. As a result, many homes are perpetually filled with toxic wood smoke that causes serious health problems, particularly for women and children. Tuberculosis is common and children often die from pneumonia, and commonly suffer from eye infections, chronic respiratory illness and other health problems. It is estimated that the inhalation of the smoke shortens the average person’s life by ten to fifteen years. With a simple masonry stove, the situation is improved dramatically. The smoke form cooking fires now travels up through the stovepipe, leaving the house relatively smoke-free, resulting in less disease, fewer burns from fires, and women are significantly less likely to prematurely lose their eyesight.</p>
		<p>With the general improvement of healthier living, the family, children are able to attend school more often and parents are more productive. Because masonry cook stoves use about 50% less fuel than three-stone fires, families are less burdened by the need to gather wood and carry it long distances on their backs. In an area where deforestation is a major problem, the stoves also help save precious natural resources. The goal of the “Masons on a Mission,” is to not leave a village until everyone who needs a new stove gets one. The group typically travels to Guatemala in January or February and stays for one week at a time, building 20 to 30 stoves. Manley warns volunteers before departing on the voyage to prepare to work in “funky” villages where the water and food can be harmful to one’s health and points out that it is not always an uplifting experience, due to the working conditions and the sad state of impoverished villages.</p>
		<p>The villagers have made amazing transitions to modern day technology, “ said Fakhoorian. “They have never had a land line phone, but they do have cell phones. It is quite surprising to see someone who lives in an adobe compound talking on a cell phone.” She told how the villagers were acquainted with some forms of modern technology, yet things that are used on a daily basis, such as the open air fire pits, were outdated and a danger to their health.</p>
		<p>Fakhoorian told how the conditions in which the villagers lives may not be lavish, but she will forever hold in her memories the beauty of the Guatemalan highland villages. She described the scenery as surreal. She shared one particular memory of standing in the center of a Guatemalan courtyard which overlooked the beautiful earthen landscapes. She said her description of the adobe compound may be a striking contrast to what the villagers see.</p>
		<p>“Everyone take things they see or use daily for granted, whether is is a refrigerator, clothes to wear, or food to eat.” She say the villagers most likely take for granted the natural beauty of their land, which she describe as simply breath-taking, with adobe huts marching down a volcanic ridge with a variety of rust colored tin roofs. Or the open air compounds, where the children ran, laughed, and played, their laughter ringing through the air as chickens scurried about. In the distance she told how she witnessed the vibrant colors of the outlying landscape which included active volcanoes emitting puffs of smoke, coffee plantations, and the sunsets which shed a rainbow of bright, cheerful colors across the sky.</p>
		<p>Fakhoorian says that even though the village was poverty-stricken, the beauty she witnessed was truly a million dollar view. She told how  the villagers had given her the most valuable memory of all. “The social interactions I shared with the families there have changed my heart forever.”</p>
          </div>
